### PR TITLE
Remove IPC listener on timeout Fixes #161

### LINKED ISSUE #161: Async throws "Callback was already called." when ready event times out
The IPC listener needs to be removed when the callback function is invoked because of a timeout.  When it is invoked a second time an uncaught exception is thrown.

### PR DESCRIPTION
**Pull request by codecounselor**

### CODE REVIEW

File: lib/exportJob.js [hunk 1]
```diff
@@ -422,37 +428,47 @@ class ExportJob extends EventEmitter {
...
+
+    // clear the timeout as soon as we get the ready event from the browser
     this.once('window.event.wait.end', () => clearTimeout(timeout))
+
     window.webContents.executeJavaScript(cmd)
   }
 
+  _cancelReadyEventTimeout (eventName, ipcListener, generateFunction) {
+    this.emit('window.event.wait.timeout', {eventName: eventName})
+    electron.ipcMain.removeListener(IPC_MAIN_CHANNEL_RENDER, ipcListener)
```
Comment (codecounselor) [inline lib/exportJob.js]: This was what was added to fix the issue

File: lib/exportJob.js [hunk 2]
```diff
@@ -396,6 +401,7 @@ class ExportJob extends EventEmitter {
     if (this.args.disableCache) {
       loadOpts.extraHeaders += 'pragma: no-cache\n'
     }
+    this.emit(`${eventPrefix}loadurl`, { url: url })
```
Comment (codecounselor) [inline lib/exportJob.js]: added for clients to have a bit more context when logging events
