### PR TITLE
hung window cleanup, improved code docs. Fixes #163

### LINKED ISSUE #163: Improve Memory Management
Things can go wrong and jobs can terminate abruptly.  If the caller does not get a reference to the job back or does not invoke `job.destroy()` windows can remain open indefinitely.  This results in memory leaks as the process continues to run.

Windows that remain open beyond a specified threshold should be automatically terminated.  Subsequently, the owning job should also be freed up for garbage collection.

There should be a new event that clients can observe when this happens

### PR DESCRIPTION
**Pull request by codecounselor**

### CODE REVIEW

File: lib/exportJob.js [hunk 1]
```diff
@@ -19,17 +19,70 @@ const logger = debug('electronpdf:')
 const wargs = require('./args')
 
 // CONSTANTS
+/** Used to calculate browser dimensions based on PDF size */
 const HTML_DPI = 96
+/** Interval for which to check for hung windows */
```
Comment (mattsgarlata) [inline lib/exportJob.js]: I think it would be helpful to list the units, and what 30,000 translates into  Same comment for HUNG_WINDOW_THRESHOLD.
