### PR TITLE
Fixes #163; Created new windowMaid.js 

### LINKED ISSUE #163: Improve Memory Management
Things can go wrong and jobs can terminate abruptly.  If the caller does not get a reference to the job back or does not invoke `job.destroy()` windows can remain open indefinitely.  This results in memory leaks as the process continues to run.

Windows that remain open beyond a specified threshold should be automatically terminated.  Subsequently, the owning job should also be freed up for garbage collection.

There should be a new event that clients can observe when this happens

### PR DESCRIPTION
**Pull request by codecounselor**

### CODE REVIEW

File: lib/windowMaid.js [hunk 1]
```diff
@@ -18,11 +18,11 @@ class WindowMaid {
    * When a job creates a window it invokes this method so any memory leaks
    * due to hung windows are prevented.  This can happen if an uncaught
    * exception occurs and job.destroy() is never invoked.
-   * @param job
+   * @param exportJob the ExportJob instance, it must have a window reference set
```
Comment (mattsgarlata) [inline lib/windowMaid.js]: Much clearer name.  Nice

**Comment by mattsgarlata** [comment]
+1

File: lib/windowMaid.js [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+const logger = debug('electronpdf:')
+
+/** How long a window can remain open before it is terminated, in milliseconds */
+const HUNG_WINDOW_THRESHOLD = process.env.ELECTRONPDF_WINDOW_LIFE_THRESHOLD || 1000 * 60 * 5 /* minutes */
+
+// Window Cache - Keep track of all windows created, and if any get stuck close
+// them
+const windowCache = {}
+
+class WindowMaid {
```
Comment (mattsgarlata) [inline lib/windowMaid.js]: Great abstraction and name

Comment (mattsgarlata) [inline lib/windowMaid.js]: It looks like everything in this class is accessed statically, so you could also set this up as just a simple object.  Since the object isn't intended to be instantiated, it may be a bit more self-documenting that way.

```
var windowMaid = {
    registerOpenWindow: function() {}, //etc
}
module.exports = windowMaid
```

Comment (codecounselor) [inline lib/windowMaid.js]: I've been using Classes in this module.  Is there a real benefit to using an object literal instead of the class? Or you just think its a bit more concise?

Comment (mattsgarlata) [inline lib/windowMaid.js]: I think there are a couple benefits to using an object literal:
- It's more concise, and follows the KISS principle
- It makes the code more self-documenting by clearly indicating the intent.  Usually classes are intended to be instantiated.  If it's just a simple object, there's no chance anyone can try to instantiate it because that would be impossible.

Comment (codecounselor) [inline lib/windowMaid.js]: I don't see how the `static` keywords make it any more complex, but I don't mind changing it either so I'll do what you suggest.
And if it was part of a public API I think the argument about instantiation makes great sense.  Since it's not in this case I'm not super concerned about that.

**Comment by mattsgarlata** [comment]
+1
